feat: update footer content
codelearncreate/weavly.org pull request #853
Opened 2023-09-25 18:24 UTC by chosww

Update footer content based on changes requested on #851
Update a section in About Us page based on changes requested on #852

2023-09-25 18:27 UTC, chosww commented
Hey @sepidehshahi, while we are waiting for the additional content from Colin, I updated the footer and it has some layout changes; could you check the deploy-preview site from this PR to check if the layout looks good?

2023-09-27 16:54 UTC, sepidehshahi commented
@chosww the footer looks good. Thanks

2024-03-11 17:52 UTC, michelled commented
@chosww can you replace the IDRC project lead email with weavly@idrc.ocadu.ca and remove reference to the 'Accessible Technology Program' - I think CanCode was a different program but also from ISED.

2024-03-11 19:08 UTC, michelled commented
@chosww the email address should be weavly@idrc.ocadu.ca

2024-03-11 19:19 UTC, greatislander requested changes
Some minor CSS changes.

2024-03-11 19:19 UTC, greatislander commented on src/assets/styles/layout/_footer.scss
>      grid-template-rows: repeat(2, auto);
I think this doesn't need to be set to `display: grid` as it's only rows now. Instead it could be flex with `flex-direction column`  and you could change `gap` to `--space-lg` (as we are only concerned with a vertical gap).

2024-03-11 19:44 UTC, greatislander approved these changes

2024-03-11 19:44 UTC, merged

2024-03-12 00:49 UTC, chosww commented
> @chosww the email address should be [weavly@idrc.ocadu.ca](mailto:weavly@idrc.ocadu.ca)

Sorry Michelle, I totally missed your comment. I opened another PR to address this.